version: 2
updates:
- package-ecosystem: docker
  directory: "/ssh"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/trx"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/upx"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/socat"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/remarkjs"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/sed"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/raspbian"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/nodejs-ci-build"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/man"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/jwt"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/gomplate-ci-build"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/github_changelog_generator"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/figlet"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/dockerfiles-builder"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/caddyproxy"
  schedule:
    interval: daily
    time: "02:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 10
