version: 1
update_configs:
  - package_manager: "docker"
    directory: "/caddyproxy"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/dockerfiles-builder"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/figlet"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/github_changelog_generator"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/gomplate-ci-build"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/jwt"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/man"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/nodejs-ci-build"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/raspbian"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/remarkjs"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/sed"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/socat"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/ssh"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/trx"
    update_schedule: "daily"
  - package_manager: "docker"
    directory: "/upx"
    update_schedule: "daily"
