
name: Docker Build
on: push

jobs:
  docker-build-dockerfiles-builder:
    name: docker build dockerfiles-builder
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/dockerfiles-builder:latest
    env:
      BASHBREW_LIBRARY: ./library
      BASHBREW_NAMESPACE: hairyhenderson
    steps:
    - uses: actions/checkout@master
    - name: build
      run: make dockerfiles-builder/image.iid
    - name: tag
      run: docker tag $(< dockerfiles-builder/image.iid) ghcr.io/hairyhenderson/dockerfiles-builder
    - name: login
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: docker push
      run: docker push ghcr.io/hairyhenderson/dockerfiles-builder
      if: github.ref == 'refs/heads/master' && github.repository == 'hairyhenderson/dockerfiles'
  docker-build-figlet:
    name: docker build figlet
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/dockerfiles-builder:latest
    env:
      BASHBREW_LIBRARY: ./library
      BASHBREW_NAMESPACE: hairyhenderson
    steps:
    - uses: actions/checkout@master
    - name: build
      run: make figlet/image.iid
    - name: tag
      run: docker tag $(< figlet/image.iid) ghcr.io/hairyhenderson/figlet
    - name: login
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: docker push
      run: docker push ghcr.io/hairyhenderson/figlet
      if: github.ref == 'refs/heads/master' && github.repository == 'hairyhenderson/dockerfiles'
  docker-build-github_changelog_generator:
    name: docker build github_changelog_generator
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/dockerfiles-builder:latest
    env:
      BASHBREW_LIBRARY: ./library
      BASHBREW_NAMESPACE: hairyhenderson
    steps:
    - uses: actions/checkout@master
    - name: build
      run: make github_changelog_generator/image.iid
    - name: tag
      run: docker tag $(< github_changelog_generator/image.iid) ghcr.io/hairyhenderson/github_changelog_generator
    - name: login
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: docker push
      run: docker push ghcr.io/hairyhenderson/github_changelog_generator
      if: github.ref == 'refs/heads/master' && github.repository == 'hairyhenderson/dockerfiles'
  docker-build-gomplate-ci-build:
    name: docker build gomplate-ci-build
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/dockerfiles-builder:latest
    env:
      BASHBREW_LIBRARY: ./library
      BASHBREW_NAMESPACE: hairyhenderson
    steps:
    - uses: actions/checkout@master
    - name: build
      run: make gomplate-ci-build/image.iid
    - name: tag
      run: docker tag $(< gomplate-ci-build/image.iid) ghcr.io/hairyhenderson/gomplate-ci-build
    - name: login
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: docker push
      run: docker push ghcr.io/hairyhenderson/gomplate-ci-build
      if: github.ref == 'refs/heads/master' && github.repository == 'hairyhenderson/dockerfiles'
  docker-build-jwt:
    name: docker build jwt
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/dockerfiles-builder:latest
    env:
      BASHBREW_LIBRARY: ./library
      BASHBREW_NAMESPACE: hairyhenderson
    steps:
    - uses: actions/checkout@master
    - name: build
      run: make jwt/image.iid
    - name: tag
      run: docker tag $(< jwt/image.iid) ghcr.io/hairyhenderson/jwt
    - name: login
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: docker push
      run: docker push ghcr.io/hairyhenderson/jwt
      if: github.ref == 'refs/heads/master' && github.repository == 'hairyhenderson/dockerfiles'
  docker-build-man:
    name: docker build man
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/dockerfiles-builder:latest
    env:
      BASHBREW_LIBRARY: ./library
      BASHBREW_NAMESPACE: hairyhenderson
    steps:
    - uses: actions/checkout@master
    - name: build
      run: make man/image.iid
    - name: tag
      run: docker tag $(< man/image.iid) ghcr.io/hairyhenderson/man
    - name: login
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: docker push
      run: docker push ghcr.io/hairyhenderson/man
      if: github.ref == 'refs/heads/master' && github.repository == 'hairyhenderson/dockerfiles'
  docker-build-nodejs-ci-build:
    name: docker build nodejs-ci-build
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/dockerfiles-builder:latest
    env:
      BASHBREW_LIBRARY: ./library
      BASHBREW_NAMESPACE: hairyhenderson
    steps:
    - uses: actions/checkout@master
    - name: build
      run: make nodejs-ci-build/image.iid
    - name: tag
      run: docker tag $(< nodejs-ci-build/image.iid) ghcr.io/hairyhenderson/nodejs-ci-build
    - name: login
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: docker push
      run: docker push ghcr.io/hairyhenderson/nodejs-ci-build
      if: github.ref == 'refs/heads/master' && github.repository == 'hairyhenderson/dockerfiles'
  docker-build-raspbian:
    name: docker build raspbian
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/dockerfiles-builder:latest
    env:
      BASHBREW_LIBRARY: ./library
      BASHBREW_NAMESPACE: hairyhenderson
    steps:
    - uses: actions/checkout@master
    - name: build
      run: make raspbian/image.iid
    - name: tag
      run: docker tag $(< raspbian/image.iid) ghcr.io/hairyhenderson/raspbian
    - name: login
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: docker push
      run: docker push ghcr.io/hairyhenderson/raspbian
      if: github.ref == 'refs/heads/master' && github.repository == 'hairyhenderson/dockerfiles'
  docker-build-remarkjs:
    name: docker build remarkjs
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/dockerfiles-builder:latest
    env:
      BASHBREW_LIBRARY: ./library
      BASHBREW_NAMESPACE: hairyhenderson
    steps:
    - uses: actions/checkout@master
    - name: build
      run: make remarkjs/image.iid
    - name: tag
      run: docker tag $(< remarkjs/image.iid) ghcr.io/hairyhenderson/remarkjs
    - name: login
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: docker push
      run: docker push ghcr.io/hairyhenderson/remarkjs
      if: github.ref == 'refs/heads/master' && github.repository == 'hairyhenderson/dockerfiles'
  docker-build-sed:
    name: docker build sed
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/dockerfiles-builder:latest
    env:
      BASHBREW_LIBRARY: ./library
      BASHBREW_NAMESPACE: hairyhenderson
    steps:
    - uses: actions/checkout@master
    - name: build
      run: make sed/image.iid
    - name: tag
      run: docker tag $(< sed/image.iid) ghcr.io/hairyhenderson/sed
    - name: login
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: docker push
      run: docker push ghcr.io/hairyhenderson/sed
      if: github.ref == 'refs/heads/master' && github.repository == 'hairyhenderson/dockerfiles'
  docker-build-socat:
    name: docker build socat
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/dockerfiles-builder:latest
    env:
      BASHBREW_LIBRARY: ./library
      BASHBREW_NAMESPACE: hairyhenderson
    steps:
    - uses: actions/checkout@master
    - name: build
      run: make socat/image.iid
    - name: tag
      run: docker tag $(< socat/image.iid) ghcr.io/hairyhenderson/socat
    - name: login
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: docker push
      run: docker push ghcr.io/hairyhenderson/socat
      if: github.ref == 'refs/heads/master' && github.repository == 'hairyhenderson/dockerfiles'
  docker-build-ssh:
    name: docker build ssh
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/dockerfiles-builder:latest
    env:
      BASHBREW_LIBRARY: ./library
      BASHBREW_NAMESPACE: hairyhenderson
    steps:
    - uses: actions/checkout@master
    - name: build
      run: make ssh/image.iid
    - name: tag
      run: docker tag $(< ssh/image.iid) ghcr.io/hairyhenderson/ssh
    - name: login
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: docker push
      run: docker push ghcr.io/hairyhenderson/ssh
      if: github.ref == 'refs/heads/master' && github.repository == 'hairyhenderson/dockerfiles'
  docker-build-trx:
    name: docker build trx
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/dockerfiles-builder:latest
    env:
      BASHBREW_LIBRARY: ./library
      BASHBREW_NAMESPACE: hairyhenderson
    steps:
    - uses: actions/checkout@master
    - name: build
      run: make trx/image.iid
    - name: tag
      run: docker tag $(< trx/image.iid) ghcr.io/hairyhenderson/trx
    - name: login
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: docker push
      run: docker push ghcr.io/hairyhenderson/trx
      if: github.ref == 'refs/heads/master' && github.repository == 'hairyhenderson/dockerfiles'
  docker-build-upx:
    name: docker build upx
    runs-on: ubuntu-latest
    container:
      image: hairyhenderson/dockerfiles-builder:latest
    env:
      BASHBREW_LIBRARY: ./library
      BASHBREW_NAMESPACE: hairyhenderson
    steps:
    - uses: actions/checkout@master
    - name: build
      run: bashbrew build upx
    - name: tag
      run: bashbrew tag --target-namespace ghcr.io/hairyhenderson upx
    - name: login
      run: |
        echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ github.actor }} --password-stdin
      if: github.repository == 'hairyhenderson/dockerfiles' && github.actor == 'hairyhenderson'
    - name: push
      run: |
        bashbrew push --dry-run upx
        bashbrew push --dry-run --target-namespace ghcr.io/hairyhenderson upx
      if: github.ref != 'refs/heads/master' && github.repository == 'hairyhenderson/dockerfiles' && github.actor == 'hairyhenderson'
    - name: push
      run: |
        bashbrew push upx
        bashbrew push --target-namespace ghcr.io/hairyhenderson upx
      if: github.ref == 'refs/heads/master' && github.repository == 'hairyhenderson/dockerfiles'
