name: New workflow
on: push

jobs:
  dockerBuild:
    name: build dockerfiles
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: docker build
      uses: actions/docker/cli@master
      with:
        args: build -f gomplate-ci-build/Dockerfile -t hairyhenderson/gomplate-ci-build gomplate-ci-build
